server:
  port: 8071

spring:
  application:
    name: "underwriter-microservice"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://${DB_CONTAINER_NAME}:3306/alinedb"
    initialization-mode: always


app:
  email:
    enable: true
    from: "no-reply@alinefinancial.com"
  aws:
    email:
      template-bucket-name: "aline-email-templates"
    credentials:
      access-key-id: "${APP_USER_ACCESS_KEY}"
      secret-access-key: "${APP_USER_SECRET_KEY}"
  landing-portal: "${PORTAL_LANDING}"
  member-dashboard: "${PORTAL_DASHBOARD}"
  security:
    secret-key: "${SECRET_KEY}"
    jwt:
      secret-key: "${SECRET_KEY}"

